name: Ruby Heads Matrix

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - '*-stable'
      - '*-dev'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rubygems:
          - latest
        bundler:
          - latest
        gemfile:
          - vanilla
        ruby:
          - head
          - truffleruby-head
          # TODO: try jruby again someday.
          # - jruby-head

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
