name: Ruby & Rails Current Matrix

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - '*-stable'
      - '*-dev'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} & Rails ${{ matrix.rails }} ${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      # rspec-rails uses RAILS_VERSION internally
      RAILS_VERSION: "~> ${{ matrix.rails }}"
      # Our spec suite (not runtime code) uses RAILS_MAJOR_MINOR internally
      RAILS_MAJOR_MINOR: ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: "3.3"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
            rails: "7.1"
          - ruby: "3.3"
            appraisal: "rails-7-0"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
            rails: "7.0"
          - ruby: "3.2"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
            rails: "7.1"
          - ruby: "3.2"
            appraisal: "rails-7-0"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
            rails: "7.0"
          #- '3.1' - Rails 7.1 on Ruby 3.1 tests are run by coverage.yml
          - ruby: "3.1"
            appraisal: "rails-7-0"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
            rails: "7.0"
          - ruby: "truffleruby"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
            rails: "7.1"
# TODO: try jruby again someday.
#          - ruby: "jruby"
#            appraisal: "rails-7-1"
#            rubygems: latest
#            bundler: latest
#            gemfile: vanilla
#            rails: "7.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/cache@v4
        id: cache
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-${{matrix.ruby}}-${{matrix.appraisal}}-${{ hashFiles('gemfiles/*.gemfile.lock') }}
      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: false
      - name: Bundle for Appraisal ${{ matrix.appraisal }} (Rails v${{ matrix.rails}})
        run: bundle
      - name: Install Appraisal ${{ matrix.appraisal }} (Rails v${{ matrix.rails}}) dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run tests ${{ matrix.appraisal }} (Rails v${{ matrix.rails}})
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec rake test
